AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hello_world.app.lambda_handler
      Runtime: python3.11
      CodeUri: hello_world/
      Description: A Lambda function using Powertools and tested with pytest
      MemorySize: 128
      Environment:
        Variables:
          S3_FILE_PATH: "s3://your-bucket/path/to/file.txt"   # Update this value as needed
      VpcConfig:
        SubnetIds:
          - YOUR_SUBNET_ID_1
          - YOUR_SUBNET_ID_2
        SecurityGroupIds:
          - YOUR_SECURITY_GROUP_ID
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 12 * * ? *)
            # Runs at 12:00 PM UTC every day. Adjust as needed.

Outputs:
  LambdaScheduleRule:
    Description: "EventBridge rule for scheduled Lambda"
    Value: !Ref HelloWorldFunction
